app_ajax/urls.py
from django.urls import path
from . import views


app_name = 'app_ajax'

urlpatterns = [
    path("", views.searchPage, name = 'home'),
    path("search", views.search, name = 'search'),
    
]

app_jquery/urls.py
from django.urls import path
from . import views


app_name = 'app_jquery'

urlpatterns = [
    path("", views.story7, name = 'story7'),
    
]

app_login/urls.py
from django.urls import path
from . import views


app_name = 'app_login'

urlpatterns = [
    path('login/', views.login_view, name = 'login'),
    path('', views.home, name = 'home' ),
    path('logout/', views.logout_view, name = 'logout'),
    path('signup/', views.signUp_view, name = 'signup' )
]

app_test/urls.py
from django.urls import path
from . import views


app_name = 'app_test'

urlpatterns = [
    path("", views.home, name = 'home'),
    
]

ppw_story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_test.urls')),
    path('story7/', include('app_jquery.urls')),
    path('story8/', include('app_ajax.urls')),
    path("story9/", include('app_login.urls')),

]   

app_ajax/models.py
from django.db import models

# Create your models here.

app_jquery/models.py
from django.db import models

# Create your models here.

app_login/models.py
from django.db import models

# Create your models here.

app_test/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    isi_status = models.TextField(max_length = 300)
    tanggal = models.DateTimeField(auto_now_add = True)
    
    def __str__(self):
        return "{},{}".format(self.isi_status, self.tanggal)

app_test/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['isi_status']

app_ajax/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests

# Create your views here.
def searchPage(request):
    return render(request, "app_ajax/base.html")

def search(request):
    key = request.GET['key']
    url = 'https://www.googleapis.com/books/v1/volumes?q=' + key
    response = requests.get(url)
    response_json = response.json()

    return JsonResponse(response_json)

app_jquery/views.py
from django.shortcuts import render

# Create your views here.
def story7(request):
    return render(request, "app_jquery/base.html")

app_login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required


# Create your views here.
def home(request):
    if request.user.is_authenticated:
        return render(request, "app_login/home.html")
    return redirect('/story9/login/')

def signUp_view(request):
    if request.user.is_authenticated:
        return redirect('/story9/')

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/story9/login/')
    else:
        form = UserCreationForm()
    return render(request, 'app_login/signup.html', {'form': form})


def login_view(request):
    if request.user.is_authenticated:
        return redirect('/story9/')

    if request.method == "POST":
        print(request.POST)
        form = AuthenticationForm(data = request.POST)
        
        if form.is_valid():
            user = form.get_user()
            print(user)
            login(request, user)
            return redirect('/story9/')
    else:
        form = AuthenticationForm()
    return render(request, "app_login/login.html", {"form" : form })

def logout_view(request):
    logout(request)
    return redirect("/story9/login")
        

app_test/views.py
from django.shortcuts import render, redirect
from .models import Status
from .forms import StatusForm

# Create your views here.
def home(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('app_test:home')
    else:
        form = StatusForm()
        all_status = Status.objects.all()
        return render(request, 'home.html', {'form':form, 'statuses' : all_status})

app_ajax/templates/app_ajax/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src = "{% static 'js/ajax-jquer.js' %}"></script>
    <script src="https://kit.fontawesome.com/bfb096346d.js" crossorigin="anonymous"></script>
    <title>Search Book</title>
</head>
<body class="bg-secondary">
    <h1 class=" mt-2 mb-2 text-center">Search Books</h1>
    
    <div class="d-flex justify-content-center">
      <div class="input-group mb-3 ml-1 " style="width: 50vw;">
          <input id = "searchBar" type="text" class="form-control">
          <div class="input-group-append">
            <button id = "submit" class="btn btn-primary" type="button" id="button-addon2"><i class="fas fa-search"></i></button>
          </div>
      </div>
    </div>

      
    <table id = "result" class=" table table-sm table-bordered table-striped table-hover table-dark">
            <thead>
              <tr>
                <th scope="col">No.</th>
                <th scope="col">Title</th>
                <th scope="col">Thumbnail</th>
                <th scope="col">Authors</th>
                <th scope="col">More Info</th>
              </tr>
            </thead>
            <tbody id = content>
            </tbody>
    </table>


</body>
</html>

app_jquery/templates/app_jquery/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel = "stylesheet" type="text/css" href="{% static 'css/jquer.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src = "{% static 'js/app_jquer.js' %}"></script>
    <script src="https://kit.fontawesome.com/bfb096346d.js" crossorigin="anonymous"></script>
    <title>Story 7</title>
</head>
<body class="d-flex flex-column ">
    <div class="pt-1 mr-0 d-flex flex-row-reverse">
        <p class= "mt-auto mb-auto ml-2 mr-1">Change Theme</p>
        <label class="switch mt-auto mb-auto ">
            <input id = "theme" type="checkbox">
            <span class="slider round"></span>
        </label>
    </div>
    <h1 class="text-center mt-4">Halo, Namaku Rafif</h1>
    <div class = "accordion d-flex flex-column mt-4">
        <h3><span class="ml-2"><i class="fa fa-angle-right mr-1"></i></span>Aktivitas </h3>
        <div class="mb-1"> 
            <ul>
                <li>Menonton Youtube Genre "Edukasi"</li>
                <li>Flag Football (Sudah Jarang)</li>
                <li>Mantengin Promo Go-Food & Grab</li>
                <li>Membaca Komik Jepun</li>
                <li>Menonton Kartun Jepun</li>
            </ul>
        </div>
        <h3><span class="ml-2"><i class="fa fa-angle-right mr-1"></i></span>Organisasi/Kepanitiaan</h3>
        <div class="mb-1"> 
            <ul>
                <li>Anggota Klub Fisika SMA</li>
                <li>Anggota Paguyuban Sumatera Selatan  UI (KEMAS UI)</li>
                <li>Member Klub Flag Football UI</li>
            </ul>
        </div >
        <h3><span class="ml-2"><i class="fa fa-angle-right mr-1"></i></span>Prestasi</h3>
        <div class="mb-1"> 
            <ul>
                <li>Juara 10 OSK Fisika 2016</li>
                <li>Mengikuti OSN Fisika 2017</li>
            </ul>
        </div>
    </div>

    
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

app_login/templates/app_login/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Home</title>
</head>
<body>
    <h1>Welcome, {{user}}</h1>
    <a href = "{% url 'app_login:logout' %}"><button id = "but-out" type="submit" class="btn btn-primary">Logout</button></a>
</body>
</html>

app_login/templates/app_login/login.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Login</title>
</head>
<body>
    <h1 class = "text-center" >Login</h1>
    <div class = "justify-content-center d-flex flex-row">
        <form action="{% url 'app_login:login' %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <div class = "text-center">
            <button id = "but-log" type="submit" class="btn btn-primary">Login</button>
        </div>
        <div class = "text-right mt-2">
            <a id = "link-sign" href = "{% url 'app_login:signup' %}">Sign Up>>></a>
        </div>
        </form> 
    </div>
</body>
</html>

app_login/templates/app_login/signup.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Sign Up</title>
</head>
<body>
    <h1 class = "text-center">Sign Up</h1>
    <div class = "justify-content-center row">
        <form action="{% url 'app_login:signup' %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <div class = "text-center">
            <button id = "but-sign" type="submit" class="btn btn-primary">Sign Up</button>
        </div>
        <div class = "text-right mt-2">
            <a id ="link-log" href = "{% url 'app_login:login' %}">Login>>></a>
        </div>
        </form> 
    </div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>Halo, apa kabar?</h1>
    </div>
    <div style="display: flex;">
        <div>
            <form method="POST">
                {% csrf_token %}
                <p>Status :</p>
                {{form.isi_status}}
                <div>
                    <input id = "submit" type="submit" value="Submit">
                </div>  
            </form>
        </div>
        {% if statuses.count > 0  %}
         <div style="margin-left:100px; ">
            <h3>Status</h3>
            <div style="height: 150px; width: 300px; overflow: auto;">
                {% for status  in statuses reversed %}
                <div>
                    <p>{{status.tanggal}}</p>
                    <p>{{status.isi_status}}</p>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
       
    </div>
    
    
    
</body>
</html>